version: '3.9'

services:
  vue:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: seointro-client
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=production
      - SERVER_ADDRESS=http://nodejs:8081 

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s    
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./ubunto/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - /etc/letsencrypt:/etc/letsencrypt ubunto\nginx\nginx.conf
      - ./ubunto/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - vue   
    command: ["nginx", "-g", "daemon off;"]   
