name: Docker Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker-repo:seointro-client -f Dockerfile .
          docker tag docker-repo:seointro-client ${{ secrets.DOCKERHUB_USERNAME }}/docker-repo:seointro-client
          docker tag docker-repo:seointro-client ${{ secrets.DOCKERHUB_USERNAME }}/docker-repo:${{ github.sha }}
        
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-repo:seointro-client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-repo:${{ github.sha }}
